<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
	Copyright (c) 2011 Lonnie Ezell

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:
	
	The above copyright notice and this permission notice shall be included in
	all copies or substantial portions of the Software.
	
	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
	THE SOFTWARE.
*/

$config['address.countries'] = array(
	'AF' => array('name' => 'AFGHANISTAN', 'printable' => '阿富汗', 'iso3' => 'AFG'),
	'AL' => array('name' => 'ALBANIA', 'printable' => '阿爾巴尼亞', 'iso3' => 'ALB'),
	'DZ' => array('name' => 'ALGERIA', 'printable' => '阿爾及利亞', 'iso3' => 'DZA'),
	'AS' => array('name' => 'AMERICAN SAMOA', 'printable' => '美屬薩摩亞', 'iso3' => 'ASM'),
	'AD' => array('name' => 'ANDORRA', 'printable' => '安道爾', 'iso3' => 'AND'),
	'AO' => array('name' => 'ANGOLA', 'printable' => '安哥拉', 'iso3' => 'AGO'),
	'AI' => array('name' => 'ANGUILLA', 'printable' => '安圭拉', 'iso3' => 'AIA'),
	'AQ' => array('name' => 'ANTARCTICA', 'printable' => '南極洲', 'iso3' => NULL),
	'AG' => array('name' => 'ANTIGUA AND BARBUDA', 'printable' => '安提瓜和巴布達', 'iso3' => 'ATG'),
	'AR' => array('name' => 'ARGENTINA', 'printable' => '阿根廷', 'iso3' => 'ARG'),
	'AM' => array('name' => 'ARMENIA', 'printable' => '亞美尼亞', 'iso3' => 'ARM'),
	'AW' => array('name' => 'ARUBA', 'printable' => '阿魯巴', 'iso3' => 'ABW'),
	'AU' => array('name' => 'AUSTRALIA', 'printable' => '澳大利亞', 'iso3' => 'AUS'),
	'AT' => array('name' => 'AUSTRIA', 'printable' => '奧地利', 'iso3' => 'AUT'),
	'AZ' => array('name' => 'AZERBAIJAN', 'printable' => '阿塞拜疆', 'iso3' => 'AZE'),
	'BS' => array('name' => 'BAHAMAS', 'printable' => '巴哈馬', 'iso3' => 'BHS'),
	'BH' => array('name' => 'BAHRAIN', 'printable' => '巴林', 'iso3' => 'BHR'),
	'BD' => array('name' => 'BANGLADESH', 'printable' => '孟加拉國', 'iso3' => 'BGD'),
	'BB' => array('name' => 'BARBADOS', 'printable' => '巴巴多斯', 'iso3' => 'BRB'),
	'BY' => array('name' => 'BELARUS', 'printable' => '白俄羅斯', 'iso3' => 'BLR'),
	'BE' => array('name' => 'BELGIUM', 'printable' => '比利時', 'iso3' => 'BEL'),
	'BZ' => array('name' => 'BELIZE', 'printable' => '伯利茲', 'iso3' => 'BLZ'),
	'BJ' => array('name' => 'BENIN', 'printable' => '貝寧', 'iso3' => 'BEN'),
	'BM' => array('name' => 'BERMUDA', 'printable' => '百慕大', 'iso3' => 'BMU'),
	'BT' => array('name' => 'BHUTAN', 'printable' => '不丹', 'iso3' => 'BTN'),
	'BO' => array('name' => 'BOLIVIA', 'printable' => '玻利維亞', 'iso3' => 'BOL'),
	'BA' => array('name' => 'BOSNIA AND HERZEGOVINA', 'printable' => '波斯尼亞和黑塞哥維那', 'iso3' => 'BIH'),
	'BW' => array('name' => 'BOTSWANA', 'printable' => '博茨瓦納', 'iso3' => 'BWA'),
	'BV' => array('name' => 'BOUVET ISLAND', 'printable' => '布維島', 'iso3' => NULL),
	'BR' => array('name' => 'BRAZIL', 'printable' => '巴西', 'iso3' => 'BRA'),
	'IO' => array('name' => 'BRITISH INDIAN OCEAN TERRITORY', 'printable' => '英屬印度洋領地', 'iso3' => NULL),
	'BN' => array('name' => 'BRUNEI DARUSSALAM', 'printable' => '汶萊', 'iso3' => 'BRN'),
	'BG' => array('name' => 'BULGARIA', 'printable' => '保加利亞', 'iso3' => 'BGR'),
	'BF' => array('name' => 'BURKINA FASO', 'printable' => '布基納法索', 'iso3' => 'BFA'),
	'BI' => array('name' => 'BURUNDI', 'printable' => '布隆迪', 'iso3' => 'BDI'),
	'KH' => array('name' => 'CAMBODIA', 'printable' => '柬埔寨', 'iso3' => 'KHM'),
	'CM' => array('name' => 'CAMEROON', 'printable' => '喀麥隆', 'iso3' => 'CMR'),
	'CA' => array('name' => 'CANADA', 'printable' => '加拿大', 'iso3' => 'CAN'),
	'CV' => array('name' => 'CAPE VERDE', 'printable' => '佛得角', 'iso3' => 'CPV'),
	'KY' => array('name' => 'CAYMAN ISLANDS', 'printable' => '開曼群島', 'iso3' => 'CYM'),
	'CF' => array('name' => 'CENTRAL AFRICAN REPUBLIC', 'printable' => '中非共和國', 'iso3' => 'CAF'),
	'TD' => array('name' => 'CHAD', 'printable' => '乍得', 'iso3' => 'TCD'),
	'CL' => array('name' => 'CHILE', 'printable' => '智利', 'iso3' => 'CHL'),
	'CN' => array('name' => 'CHINA', 'printable' => '中國', 'iso3' => 'CHN'),
	'CX' => array('name' => 'CHRISTMAS ISLAND', 'printable' => '聖誕島', 'iso3' => NULL),
	'CC' => array('name' => 'COCOS (KEELING) ISLANDS', 'printable' => '科科斯（基林）群島', 'iso3' => NULL),
	'CO' => array('name' => 'COLOMBIA', 'printable' => '哥倫比亞', 'iso3' => 'COL'),
	'KM' => array('name' => 'COMOROS', 'printable' => '科摩羅', 'iso3' => 'COM'),
	'CG' => array('name' => 'CONGO', 'printable' => '剛果', 'iso3' => 'COG'),
	'CD' => array('name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'printable' => '剛果，剛果民主共和國', 'iso3' => 'COD'),
	'CK' => array('name' => 'COOK ISLANDS', 'printable' => '庫克群島', 'iso3' => 'COK'),
	'CR' => array('name' => 'COSTA RICA', 'printable' => '哥斯達黎加', 'iso3' => 'CRI'),
	'CI' => array('name' => 'COTE D\'IVOIRE', 'printable' => '科特迪瓦\科特迪瓦', 'iso3' => 'CIV'),
	'HR' => array('name' => 'CROATIA', 'printable' => '克羅地亞', 'iso3' => 'HRV'),
	'CU' => array('name' => 'CUBA', 'printable' => '古巴', 'iso3' => 'CUB'),
	'CY' => array('name' => 'CYPRUS', 'printable' => '塞浦路斯', 'iso3' => 'CYP'),
	'CZ' => array('name' => 'CZECH REPUBLIC', 'printable' => '捷克共和國', 'iso3' => 'CZE'),
	'DK' => array('name' => 'DENMARK', 'printable' => '丹麥', 'iso3' => 'DNK'),
	'DJ' => array('name' => 'DJIBOUTI', 'printable' => '吉布提', 'iso3' => 'DJI'),
	'DM' => array('name' => 'DOMINICA', 'printable' => '多米尼克', 'iso3' => 'DMA'),
	'DO' => array('name' => 'DOMINICAN REPUBLIC', 'printable' => '多米尼加共和國', 'iso3' => 'DOM'),
	'EC' => array('name' => 'ECUADOR', 'printable' => '厄瓜多爾', 'iso3' => 'ECU'),
	'EG' => array('name' => 'EGYPT', 'printable' => '埃及', 'iso3' => 'EGY'),
	'SV' => array('name' => 'EL SALVADOR', 'printable' => '薩爾瓦多', 'iso3' => 'SLV'),
	'GQ' => array('name' => 'EQUATORIAL GUINEA', 'printable' => '赤道幾內亞', 'iso3' => 'GNQ'),
	'ER' => array('name' => 'ERITREA', 'printable' => '厄立特里亞', 'iso3' => 'ERI'),
	'EE' => array('name' => 'ESTONIA', 'printable' => '愛沙尼亞', 'iso3' => 'EST'),
	'ET' => array('name' => 'ETHIOPIA', 'printable' => '埃塞俄比亞', 'iso3' => 'ETH'),
	'FK' => array('name' => 'FALKLAND ISLANDS (MALVINAS)', 'printable' => '福克蘭群島（馬爾維納斯）', 'iso3' => 'FLK'),
	'FO' => array('name' => 'FAROE ISLANDS', 'printable' => '法羅群島', 'iso3' => 'FRO'),
	'FJ' => array('name' => 'FIJI', 'printable' => '斐濟', 'iso3' => 'FJI'),
	'FI' => array('name' => 'FINLAND', 'printable' => '芬蘭', 'iso3' => 'FIN'),
	'FR' => array('name' => 'FRANCE', 'printable' => '法國', 'iso3' => 'FRA'),
	'GF' => array('name' => 'FRENCH GUIANA', 'printable' => '法屬圭亞那', 'iso3' => 'GUF'),
	'PF' => array('name' => 'FRENCH POLYNESIA', 'printable' => '法屬波利尼西亞', 'iso3' => 'PYF'),
	'TF' => array('name' => 'FRENCH SOUTHERN TERRITORIES', 'printable' => '法國南部領土', 'iso3' => NULL),
	'GA' => array('name' => 'GABON', 'printable' => '加蓬', 'iso3' => 'GAB'),
	'GM' => array('name' => 'GAMBIA', 'printable' => '岡比亞', 'iso3' => 'GMB'),
	'GE' => array('name' => 'GEORGIA', 'printable' => '格魯吉亞', 'iso3' => 'GEO'),
	'DE' => array('name' => 'GERMANY', 'printable' => '德國', 'iso3' => 'DEU'),
	'GH' => array('name' => 'GHANA', 'printable' => '加納', 'iso3' => 'GHA'),
	'GI' => array('name' => 'GIBRALTAR', 'printable' => '直布羅陀', 'iso3' => 'GIB'),
	'GR' => array('name' => 'GREECE', 'printable' => '希臘', 'iso3' => 'GRC'),
	'GL' => array('name' => 'GREENLAND', 'printable' => '格陵蘭', 'iso3' => 'GRL'),
	'GD' => array('name' => 'GRENADA', 'printable' => '格林納達', 'iso3' => 'GRD'),
	'GP' => array('name' => 'GUADELOUPE', 'printable' => '瓜德羅普島', 'iso3' => 'GLP'),
	'GU' => array('name' => 'GUAM', 'printable' => '關島', 'iso3' => 'GUM'),
	'GT' => array('name' => 'GUATEMALA', 'printable' => '危地馬拉', 'iso3' => 'GTM'),
	'GN' => array('name' => 'GUINEA', 'printable' => '幾內亞', 'iso3' => 'GIN'),
	'GW' => array('name' => 'GUINEA-BISSAU', 'printable' => '幾內亞比紹', 'iso3' => 'GNB'),
	'GY' => array('name' => 'GUYANA', 'printable' => '圭亞那', 'iso3' => 'GUY'),
	'HT' => array('name' => 'HAITI', 'printable' => '海地', 'iso3' => 'HTI'),
	'HM' => array('name' => 'HEARD ISLAND AND MCDONALD ISLANDS', 'printable' => '赫德島和麥當勞群島', 'iso3' => NULL),
	'VA' => array('name' => 'HOLY SEE (VATICAN CITY STATE)', 'printable' => '羅馬教廷（梵蒂岡城國）', 'iso3' => 'VAT'),
	'HN' => array('name' => 'HONDURAS', 'printable' => '洪都拉斯', 'iso3' => 'HND'),
	'HK' => array('name' => 'HONG KONG', 'printable' => '香港', 'iso3' => 'HKG'),
	'HU' => array('name' => 'HUNGARY', 'printable' => '匈牙利', 'iso3' => 'HUN'),
	'IS' => array('name' => 'ICELAND', 'printable' => '冰島', 'iso3' => 'ISL'),
	'IN' => array('name' => 'INDIA', 'printable' => '印度', 'iso3' => 'IND'),
	'ID' => array('name' => 'INDONESIA', 'printable' => '印尼', 'iso3' => 'IDN'),
	'IR' => array('name' => 'IRAN, ISLAMIC REPUBLIC OF', 'printable' => '伊朗伊斯蘭共和國', 'iso3' => 'IRN'),
	'IQ' => array('name' => 'IRAQ', 'printable' => '伊拉克', 'iso3' => 'IRQ'),
	'IE' => array('name' => 'IRELAND', 'printable' => '愛爾蘭', 'iso3' => 'IRL'),
	'IL' => array('name' => 'ISRAEL', 'printable' => '以色列', 'iso3' => 'ISR'),
	'IT' => array('name' => 'ITALY', 'printable' => '意大利', 'iso3' => 'ITA'),
	'JM' => array('name' => 'JAMAICA', 'printable' => '牙買加', 'iso3' => 'JAM'),
	'JP' => array('name' => 'JAPAN', 'printable' => '日本', 'iso3' => 'JPN'),
	'JO' => array('name' => 'JORDAN', 'printable' => '約旦', 'iso3' => 'JOR'),
	'KZ' => array('name' => 'KAZAKHSTAN', 'printable' => '哈薩克斯坦', 'iso3' => 'KAZ'),
	'KE' => array('name' => 'KENYA', 'printable' => '肯尼亞', 'iso3' => 'KEN'),
	'KI' => array('name' => 'KIRIBATI', 'printable' => '基里巴斯', 'iso3' => 'KIR'),
	'KP' => array('name' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', 'printable' => '北韓', 'iso3' => 'PRK'),
	'KR' => array('name' => 'KOREA, REPUBLIC OF', 'printable' => '大韓民國', 'iso3' => 'KOR'),
	'KW' => array('name' => 'KUWAIT', 'printable' => '科威特', 'iso3' => 'KWT'),
	'KG' => array('name' => 'KYRGYZSTAN', 'printable' => '吉爾吉斯斯坦', 'iso3' => 'KGZ'),
	'LA' => array('name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'printable' => '寮國', 'iso3' => 'LAO'),
	'LV' => array('name' => 'LATVIA', 'printable' => '拉脫維亞', 'iso3' => 'LVA'),
	'LB' => array('name' => 'LEBANON', 'printable' => '黎巴嫩', 'iso3' => 'LBN'),
	'LS' => array('name' => 'LESOTHO', 'printable' => '萊索托', 'iso3' => 'LSO'),
	'LR' => array('name' => 'LIBERIA', 'printable' => '利比里亞', 'iso3' => 'LBR'),
	'LY' => array('name' => 'LIBYAN ARAB JAMAHIRIYA', 'printable' => '阿拉伯利比亞民眾國', 'iso3' => 'LBY'),
	'LI' => array('name' => 'LIECHTENSTEIN', 'printable' => '列支敦士登', 'iso3' => 'LIE'),
	'LT' => array('name' => 'LITHUANIA', 'printable' => '立陶宛', 'iso3' => 'LTU'),
	'LU' => array('name' => 'LUXEMBOURG', 'printable' => '盧森堡', 'iso3' => 'LUX'),
	'MO' => array('name' => 'MACAO', 'printable' => '澳門', 'iso3' => 'MAC'),
	'MK' => array('name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'printable' => '馬其頓，前南斯拉夫的馬其頓共和國', 'iso3' => 'MKD'),
	'MG' => array('name' => 'MADAGASCAR', 'printable' => '馬達加斯加', 'iso3' => 'MDG'),
	'MW' => array('name' => 'MALAWI', 'printable' => '馬拉維', 'iso3' => 'MWI'),
	'MY' => array('name' => 'MALAYSIA', 'printable' => '馬來西亞', 'iso3' => 'MYS'),
	'MV' => array('name' => 'MALDIVES', 'printable' => '馬爾代夫', 'iso3' => 'MDV'),
	'ML' => array('name' => 'MALI', 'printable' => '馬里', 'iso3' => 'MLI'),
	'MT' => array('name' => 'MALTA', 'printable' => '馬耳他', 'iso3' => 'MLT'),
	'MH' => array('name' => 'MARSHALL ISLANDS', 'printable' => '馬紹爾群島', 'iso3' => 'MHL'),
	'MQ' => array('name' => 'MARTINIQUE', 'printable' => '馬提尼克島', 'iso3' => 'MTQ'),
	'MR' => array('name' => 'MAURITANIA', 'printable' => '毛里塔尼亞', 'iso3' => 'MRT'),
	'MU' => array('name' => 'MAURITIUS', 'printable' => '毛里求斯', 'iso3' => 'MUS'),
	'YT' => array('name' => 'MAYOTTE', 'printable' => '馬約特島', 'iso3' => NULL),
	'MX' => array('name' => 'MEXICO', 'printable' => '墨西哥', 'iso3' => 'MEX'),
	'FM' => array('name' => 'MICRONESIA, FEDERATED STATES OF', 'printable' => '密克羅尼西亞聯邦', 'iso3' => 'FSM'),
	'MD' => array('name' => 'MOLDOVA, REPUBLIC OF', 'printable' => '摩爾多瓦共和國', 'iso3' => 'MDA'),
	'MC' => array('name' => 'MONACO', 'printable' => '摩納哥', 'iso3' => 'MCO'),
	'MN' => array('name' => 'MONGOLIA', 'printable' => '蒙古', 'iso3' => 'MNG'),
	'MS' => array('name' => 'MONTSERRAT', 'printable' => '蒙特塞拉特', 'iso3' => 'MSR'),
	'MA' => array('name' => 'MOROCCO', 'printable' => '摩洛哥', 'iso3' => 'MAR'),
	'MZ' => array('name' => 'MOZAMBIQUE', 'printable' => '莫桑比克', 'iso3' => 'MOZ'),
	'MM' => array('name' => 'MYANMAR', 'printable' => '緬甸', 'iso3' => 'MMR'),
	'NA' => array('name' => 'NAMIBIA', 'printable' => '納米比亞', 'iso3' => 'NAM'),
	'NR' => array('name' => 'NAURU', 'printable' => '瑙魯', 'iso3' => 'NRU'),
	'NP' => array('name' => 'NEPAL', 'printable' => '尼泊爾', 'iso3' => 'NPL'),
	'NL' => array('name' => 'NETHERLANDS', 'printable' => '荷蘭', 'iso3' => 'NLD'),
	'AN' => array('name' => 'NETHERLANDS ANTILLES', 'printable' => '荷屬安的列斯', 'iso3' => 'ANT'),
	'NC' => array('name' => 'NEW CALEDONIA', 'printable' => '新喀裡多尼亞', 'iso3' => 'NCL'),
	'NZ' => array('name' => 'NEW ZEALAND', 'printable' => '新西蘭', 'iso3' => 'NZL'),
	'NI' => array('name' => 'NICARAGUA', 'printable' => '尼加拉瓜', 'iso3' => 'NIC'),
	'NE' => array('name' => 'NIGER', 'printable' => '尼日爾', 'iso3' => 'NER'),
	'NG' => array('name' => 'NIGERIA', 'printable' => '尼日利亞', 'iso3' => 'NGA'),
	'NU' => array('name' => 'NIUE', 'printable' => '紐埃', 'iso3' => 'NIU'),
	'NF' => array('name' => 'NORFOLK ISLAND', 'printable' => '諾福克島', 'iso3' => 'NFK'),
	'MP' => array('name' => 'NORTHERN MARIANA ISLANDS', 'printable' => '北馬里亞納群島', 'iso3' => 'MNP'),
	'NO' => array('name' => 'NORWAY', 'printable' => '挪威', 'iso3' => 'NOR'),
	'OM' => array('name' => 'OMAN', 'printable' => '阿曼', 'iso3' => 'OMN'),
	'PK' => array('name' => 'PAKISTAN', 'printable' => '巴基斯坦', 'iso3' => 'PAK'),
	'PW' => array('name' => 'PALAU', 'printable' => '帕勞', 'iso3' => 'PLW'),
	'PS' => array('name' => 'PALESTINIAN TERRITORY, OCCUPIED', 'printable' => '巴勒斯坦領土', 'iso3' => NULL),
	'PA' => array('name' => 'PANAMA', 'printable' => '巴拿馬', 'iso3' => 'PAN'),
	'PG' => array('name' => 'PAPUA NEW GUINEA', 'printable' => '巴布亞新幾內亞', 'iso3' => 'PNG'),
	'PY' => array('name' => 'PARAGUAY', 'printable' => '巴拉圭', 'iso3' => 'PRY'),
	'PE' => array('name' => 'PERU', 'printable' => '秘魯', 'iso3' => 'PER'),
	'PH' => array('name' => 'PHILIPPINES', 'printable' => '菲律賓', 'iso3' => 'PHL'),
	'PN' => array('name' => 'PITCAIRN', 'printable' => '皮特凱恩', 'iso3' => 'PCN'),
	'PL' => array('name' => 'POLAND', 'printable' => '波蘭', 'iso3' => 'POL'),
	'PT' => array('name' => 'PORTUGAL', 'printable' => '葡萄牙', 'iso3' => 'PRT'),
	'PR' => array('name' => 'PUERTO RICO', 'printable' => '波多黎各', 'iso3' => 'PRI'),
	'QA' => array('name' => 'QATAR', 'printable' => '卡塔爾', 'iso3' => 'QAT'),
	'RE' => array('name' => 'REUNION', 'printable' => '留尼旺島', 'iso3' => 'REU'),
	'RO' => array('name' => 'ROMANIA', 'printable' => '羅馬尼亞', 'iso3' => 'ROM'),
	'RU' => array('name' => 'RUSSIAN FEDERATION', 'printable' => '俄羅斯聯邦', 'iso3' => 'RUS'),
	'RW' => array('name' => 'RWANDA', 'printable' => '盧旺達', 'iso3' => 'RWA'),
	'SH' => array('name' => 'SAINT HELENA', 'printable' => '聖赫勒拿', 'iso3' => 'SHN'),
	'KN' => array('name' => 'SAINT KITTS AND NEVIS', 'printable' => '聖基茨和尼維斯', 'iso3' => 'KNA'),
	'LC' => array('name' => 'SAINT LUCIA', 'printable' => '聖盧西亞', 'iso3' => 'LCA'),
	'PM' => array('name' => 'SAINT PIERRE AND MIQUELON', 'printable' => '聖皮埃爾和密克隆', 'iso3' => 'SPM'),
	'VC' => array('name' => 'SAINT VINCENT AND THE GRENADINES', 'printable' => '聖文森特和格林納丁斯', 'iso3' => 'VCT'),
	'WS' => array('name' => 'SAMOA', 'printable' => '薩摩亞', 'iso3' => 'WSM'),
	'SM' => array('name' => 'SAN MARINO', 'printable' => '聖馬力諾', 'iso3' => 'SMR'),
	'ST' => array('name' => 'SAO TOME AND PRINCIPE', 'printable' => '聖多美和普林西比', 'iso3' => 'STP'),
	'SA' => array('name' => 'SAUDI ARABIA', 'printable' => '沙特阿拉伯', 'iso3' => 'SAU'),
	'SN' => array('name' => 'SENEGAL', 'printable' => '塞內加爾', 'iso3' => 'SEN'),
	'CS' => array('name' => 'SERBIA AND MONTENEGRO', 'printable' => '塞爾維亞和黑山', 'iso3' => NULL),
	'SC' => array('name' => 'SEYCHELLES', 'printable' => '塞舌爾', 'iso3' => 'SYC'),
	'SL' => array('name' => 'SIERRA LEONE', 'printable' => '塞拉利昂', 'iso3' => 'SLE'),
	'SG' => array('name' => 'SINGAPORE', 'printable' => '新加坡', 'iso3' => 'SGP'),
	'SK' => array('name' => 'SLOVAKIA', 'printable' => '斯洛伐克', 'iso3' => 'SVK'),
	'SI' => array('name' => 'SLOVENIA', 'printable' => '斯洛文尼亞', 'iso3' => 'SVN'),
	'SB' => array('name' => 'SOLOMON ISLANDS', 'printable' => '所羅門群島', 'iso3' => 'SLB'),
	'SO' => array('name' => 'SOMALIA', 'printable' => '索馬里', 'iso3' => 'SOM'),
	'ZA' => array('name' => 'SOUTH AFRICA', 'printable' => '南非', 'iso3' => 'ZAF'),
	'GS' => array('name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'printable' => '南喬治亞島和南桑威奇群島', 'iso3' => NULL),
	'ES' => array('name' => 'SPAIN', 'printable' => '西班牙', 'iso3' => 'ESP'),
	'LK' => array('name' => 'SRI LANKA', 'printable' => '斯里蘭卡', 'iso3' => 'LKA'),
	'SD' => array('name' => 'SUDAN', 'printable' => '蘇丹', 'iso3' => 'SDN'),
	'SR' => array('name' => 'SURINAME', 'printable' => '蘇里南', 'iso3' => 'SUR'),
	'SJ' => array('name' => 'SVALBARD AND JAN MAYEN', 'printable' => '斯瓦爾巴島和揚馬延島', 'iso3' => 'SJM'),
	'SZ' => array('name' => 'SWAZILAND', 'printable' => '斯威士蘭', 'iso3' => 'SWZ'),
	'SE' => array('name' => 'SWEDEN', 'printable' => '瑞典', 'iso3' => 'SWE'),
	'CH' => array('name' => 'SWITZERLAND', 'printable' => '瑞士', 'iso3' => 'CHE'),
	'SY' => array('name' => 'SYRIAN ARAB REPUBLIC', 'printable' => '阿拉伯敘利亞共和國', 'iso3' => 'SYR'),
	'TW' => array('name' => 'TAIWAN', 'printable' => '台灣', 'iso3' => 'TWN'),
	'TJ' => array('name' => 'TAJIKISTAN', 'printable' => '塔吉克斯坦', 'iso3' => 'TJK'),
	'TZ' => array('name' => 'TANZANIA, UNITED REPUBLIC OF', 'printable' => '坦桑尼亞聯合共和國', 'iso3' => 'TZA'),
	'TH' => array('name' => 'THAILAND', 'printable' => '泰國', 'iso3' => 'THA'),
	'TL' => array('name' => 'TIMOR-LESTE', 'printable' => '東帝汶', 'iso3' => NULL),
	'TG' => array('name' => 'TOGO', 'printable' => '多哥', 'iso3' => 'TGO'),
	'TK' => array('name' => 'TOKELAU', 'printable' => '托克勞', 'iso3' => 'TKL'),
	'TO' => array('name' => 'TONGA', 'printable' => '湯加', 'iso3' => 'TON'),
	'TT' => array('name' => 'TRINIDAD AND TOBAGO', 'printable' => '特里尼達和多巴哥', 'iso3' => 'TTO'),
	'TN' => array('name' => 'TUNISIA', 'printable' => '突尼斯', 'iso3' => 'TUN'),
	'TR' => array('name' => 'TURKEY', 'printable' => '土耳其', 'iso3' => 'TUR'),
	'TM' => array('name' => 'TURKMENISTAN', 'printable' => '土庫曼斯坦', 'iso3' => 'TKM'),
	'TC' => array('name' => 'TURKS AND CAICOS ISLANDS', 'printable' => '特克斯和凱科斯群島', 'iso3' => 'TCA'),
	'TV' => array('name' => 'TUVALU', 'printable' => '圖瓦盧', 'iso3' => 'TUV'),
	'UG' => array('name' => 'UGANDA', 'printable' => '烏干達', 'iso3' => 'UGA'),
	'UA' => array('name' => 'UKRAINE', 'printable' => '烏克蘭', 'iso3' => 'UKR'),
	'AE' => array('name' => 'UNITED ARAB EMIRATES', 'printable' => '阿拉伯聯合酋長國', 'iso3' => 'ARE'),
	'GB' => array('name' => 'UNITED KINGDOM', 'printable' => '英國', 'iso3' => 'GBR'),
	'US' => array('name' => 'UNITED STATES', 'printable' => '美國', 'iso3' => 'USA'),
	'UM' => array('name' => 'UNITED STATES MINOR OUTLYING ISLANDS', 'printable' => '美國本土外小島嶼', 'iso3' => NULL),
	'UY' => array('name' => 'URUGUAY', 'printable' => '烏拉圭', 'iso3' => 'URY'),
	'UZ' => array('name' => 'UZBEKISTAN', 'printable' => '烏茲別克斯坦', 'iso3' => 'UZB'),
	'VU' => array('name' => 'VANUATU', 'printable' => '瓦努阿圖', 'iso3' => 'VUT'),
	'VE' => array('name' => 'VENEZUELA', 'printable' => '委內瑞拉', 'iso3' => 'VEN'),
	'VN' => array('name' => 'VIET NAM', 'printable' => '越南', 'iso3' => 'VNM'),
	'VG' => array('name' => 'VIRGIN ISLANDS, BRITISH', 'printable' => '英屬維爾京群島', 'iso3' => 'VGB'),
	'VI' => array('name' => 'VIRGIN ISLANDS, U.S.', 'printable' => '美屬維爾京群島', 'iso3' => 'VIR'),
	'WF' => array('name' => 'WALLIS AND FUTUNA', 'printable' => '瓦利斯群島和富圖納群島', 'iso3' => 'WLF'),
	'EH' => array('name' => 'WESTERN SAHARA', 'printable' => '西撒哈拉', 'iso3' => 'ESH'),
	'YE' => array('name' => 'YEMEN', 'printable' => '也門', 'iso3' => 'YEM'),
	'ZM' => array('name' => 'ZAMBIA', 'printable' => '贊比亞', 'iso3' => 'ZMB'),
	'ZW' => array('name' => 'ZIMBABWE', 'printable' => '津巴布韋', 'iso3' => 'ZWE'),	
);


$config['address.states'] = array(
	'US' => array(
		'AK' => 'Alaska',
		'AL' => 'Alabama',
		'AS' => 'American Samoa',
		'AZ' => 'Arizona',
		'AR' => 'Arkansas',
		'CA' => 'California',
		'CO' => 'Colorado',
		'CT' => 'Connecticut',
		'DE' => 'Delaware',
		'DC' => 'District of Columbia',
		'FL' => 'Florida',
		'GA' => 'Georgia',
		'GU' => 'Guam',
		'HI' => 'Hawaii',
		'ID' => 'Idaho',
		'IL' => 'Illinois',
		'IN' => 'Indiana',
		'IA' => 'Iowa',
		'KS' => 'Kansas',
		'KY' => 'Kentucky',
		'LA' => 'Louisiana',
		'ME' => 'Maine',
		'MH' => 'Marshall Islands',
		'MD' => 'Maryland',
		'MA' => 'Massachusetts',
		'MI' => 'Michigan',
		'MN' => 'Minnesota',
		'MS' => 'Mississippi',
		'MO' => 'Missouri',
		'MT' => 'Montana',
		'NE' => 'Nebraska',
		'NV' => 'Nevada',
		'NH' => 'New Hampshire',
		'NJ' => 'New Jersey',
		'NM' => 'New Mexico',
		'NY' => 'New York',
		'NC' => 'North Carolina',
		'ND' => 'North Dakota',
		'MP' => 'Northern Mariana Islands',
		'OH' => 'Ohio',
		'OK' => 'Oklahoma',
		'OR' => 'Oregon',
		'PW' => 'Palau',
		'PA' => 'Pennsylvania',
		'PR' => 'Puerto Rico',
		'RI' => 'Rhode Island',
		'SC' => 'South Carolina',
		'SD' => 'South Dakota',
		'TN' => 'Tennessee',
		'TX' => 'Texas',
		'UT' => 'Utah',
		'VT' => 'Vermont',
		'VI' => 'Virgin Islands',
		'VA' => 'Virginia',
		'WA' => 'Washington',
		'WV' => 'West Virginia',
		'WI' => 'Wisconsin',
		'WY' => 'Wyoming'
	),
	'CA'	=> array(
		'AB' => 'Alberta',
		'BC' => 'British Columbia',
		'MB' => 'Manitoba',
		'NB' => 'New Brunswick',
		'NL' => 'Newfoundland and Labrador',
		'NT' => 'Northwest Territories',
		'NS' => 'Nova Scotia',
		'NU' => 'Nunavut',
		'ON' => 'Ontario',
		'PE' => 'Prince Edward Island',
		'QC' => 'Quebec',
		'SK' => 'Saskatchewan',
		'YT' => 'Yukon'
	),
	'TW'	=> array(
		'A' => '臺北市',
		'B' => '新北市',
		'C' => '臺中市',
		'D' => '臺南市',
		'E' => '高雄市',
		'F' => '基隆市',
		'G' => '新竹市',
		'H' => '嘉義市',
		'I' => '桃園縣',
		'J' => '新竹縣',
		'K' => '苗栗縣',
		'L' => '彰化縣',
		'M' => '南投縣',
		'N' => '雲林縣',
		'O' => '嘉義縣',
		'P' => '屏東縣',
		'Q' => '宜蘭縣',
		'R' => '花蓮縣',
		'S' => '臺東縣',
		'T' => '澎湖縣',
		'U' => '金門縣',
		'V' => '連江縣'
	),
	'MX'	=> array(
		'AG' => 'Aguascalientes',
		'BC' => 'Baja California Norte',
		'BS' => 'Baja California Sur',
		'CH' => 'Chihuahua',
		'CL' => 'Colima',
		'CM' => 'Campeche',
		'CO' => 'Coahuila',
		'CS' => 'Chiapas',
		'DF' => 'Distrito Federal',
		'DG' => 'Durango',
		'GR' => 'Guerrero',
		'GT' => 'Guanajuato',
		'HG' => 'Hidalgo',
		'JA' => 'Jalisco',
		'MI' => 'Michoacan',
		'MO' => 'Morelos',
		'NA' => 'Nayarit',
		'NL' => 'Nuevo Leon',
		'OA' => 'Oaxaca',
		'PU' => 'Puebla',
		'QR' => 'Quintana Roo',
		'QT' => 'Queretaro',
		'SI' => 'Sinaloa',
		'SL' => 'San Luis Potosi',
		'SO' => 'Sonora',
		'TB' => 'Tabasco',
		'TL' => 'Tlaxcala',
		'TM' => 'Tamaulipas',
		'VE' => 'Veracruz',
		'YU' => 'Yucatan',
		'ZA' => 'Zacatecas'
	),
);

